[package]
name = "kebabmaneater/expand"
description = "Expand the roblox API. Wally has a problem with types though so the signal isn't 100% typed, forced to use RBXScriptConnection instead of Signal.Signal<Instance>"
version = "0.2.1"
license = "MIT"
authors = ["Kebabmaneater"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib", "default.project.json"]

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Tree = "sleitnick/tree@1.1.0"
Trove = "sleitnick/trove@1.1.0"

[place]
shared-packages = "game.ReplicatedStorage.Packages"